nopivotcontainerd: nopivotcontainerd.o
	$(CC) $(LDFLAGS) nopivotcontainerd.o -o nopivotcontainerd

nopivotcontainerd.o: nopivotcontainerd.c
	$(CC) $(CFLAGS) -c nopivotcontainerd.c

clean:
	rm -f *.o nopivotcontainerd

